### ISSUE TITLE
프로젝트 설계

### ISSUE THREAD

**Issue by swellful** [swellful-life/md2blogger#1]
### 배경
- Google Blogger 에서는 마크다운 형식으로 포스팅을 지원하지 않음
- 일부 플랫폼에서 마크다운 기반 글 작성 및 Blogger 포스팅 기능을 제공하지만(E.g. stackedit) **이미지 복사&붙여넣기 지원이 안됨**
- 따라서 간단하게 Github Action 을 활용하여, Repo. 내 마크다운 형식으로 작성한 글을 포스팅하는 기능 구현

### 참고 링크
- NONE

### 목표 일정
- TBD

**Comment by swellful** [comment]
### 세팅이 필요한 내용들
- [ ] 구글 블로거 생성
- [ ] 구글 블로거 세팅
  - [ ] 테마 및 레이아웃 적용 : SmartMag Theme 구매 및 적용 완료
  - [ ] 외부 도메인 구매 및 연결 : GoDaddy 에서 `swellful.life` 구매 및 연동 완료
  - [ ] Google Analytics 연동
  - [ ] Google Search Console 연동
- [ ] Github Action 을 위한 Repo. 생성 : `md2blogger` (해당 Repo.)
- [ ] Github Action 설계
- [ ] Github Action 개발

**Comment by swellful** [comment]
### md2blogger 설계: Markdown -> HTML 변환
#### 메타 정보 처리
- Obsidian 의 Properties 기능을 활용해, Blogger 에 글 작성 시 필요한 메타 정보를 입력받을 수 있도록 할 예정
- Blogger API 통해 설정할 수 있는 메타 정보
  ```yaml
  {
    "kind": "blogger#post",
    "blog": {
      "id": "{BLOG_ID}"
    },
    "title": "Sample Blog Post",
    "content": "<p>This is a sample blog post content.</p>",
    "labels": ["Sample", "API Test"],
    "published": "2025-01-11T10:30:00-08:00",
    "url": "https://example.blogspot.com/custom-permalink",
    "location": {
      "name": "Seoul, South Korea",
      "lat": 37.5665,
      "lng": 126.9780
    },
    "status": "DRAFT",
    "author": {
      "id": "123456789",
      "displayName": "Your Name"
    }
  } 
  ```
- 이 중 properties 통해 설정할 메타 정보
  - `title`, `labels`, `published`, `url`, `author`

#### 포스팅 `*.md` 파일 경로 구성 및 이미지 업로드
- 우선 github repo. 를 통해 `*.md` 포맷으로 블로그 글을 작성할 예정
- custom plugin 설치를 통해 Obsidian 내 아래 기능 추가
  - Table 편집: Advanced Tables
  - github push 기능: Git
  - 미사용 이미지 삭제기능: Clear unused Images
  - 이미지 경로 커스텀 설정 : Custom Attachment Location
- 위 플러그인 사용을 통해 게시글과 이미지(첨부파일)의 경로는 아래와 같이 구성됨
  ```yaml
  posts/<LABEL>
  |-- posting1.md
  |-- assets
  |--|-- posting1          # 포스팅 파일(posting1.md) 와 같은 이름으로 폴더가 생성되며,해당 폴더 하위 첨부파일 저장
  |--|--|-- images...
  |-- <SERIES>             # 필요한 경우 시리즈를 구성할 수 있고, 해당 경로 하위에 포스팅 및 첨부파일 구성 가능
  |--|-- posting2.md      
  |--|-- assets
  |--|--|-- posting2
  |--|--|--|-- images...  
  ```

<details>
<summary>참고 이미지</summary>

<img width="790" alt="image" src="https://github.com/user-attachments/assets/11ff3799-c5eb-47d3-aafd-8e79d48472b9" />

</details>
